quotas:
  covis: 80
  pop: 30
  session_ngram: 60
  item2vec: 80
  mf_als: 60
  lightgcn: 40
  graph_ppr: 40
weights:
  covis: 1.0
  pop: 0.4
  session_ngram: 0.8
  item2vec: 0.9
  mf_als: 0.9
  lightgcn: 0.9
  graph_ppr: 0.7
K: 200
time_window_days: 60
cutoff: auto
use_heavy_models: true
random_seed: 42
jobs: -1
features:
  blocks:
    cross:
      enabled: true
dataio:
  queries:
    limit_per_split: null
  pairs:
    neg_pos_ratio: 100
    similarity:
      enabled: true
    sequence:
      last_k: [5, 15]
